---
title: Something old and something older
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 2023-03-22T14:39:55-05:00
lastmod: 2023-03-22T14:39:55-05:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

I'm co-teaching a small group learning course on critical appraisal for our MPH students. We have tried to avoid the common theme of many critical appraisal courses and journal clubs that simply try to trash whatever article is under review. Rather we divide the groups into three sections and the first one receives only an introduction to the problem, and without looking at the chosen article, discuss what sort of study design, with the associated strengths and limitations, they would consider to address the problem. The second group receives only the abstract and comments on what details they would expect top see in the article. The third group reads the whole article and in addition to highlighting its strengths and limitations tries to answer queries raised by the first 2 groups. The basic idea is not only to improve critical appraisal skills but also to think about possible research designs and the necessary compromises that are often required in doing research.    

This week one of the other co-instructors chose (for reasons that will become evident later) an older [NEJM article from 2007](https://pubmed.ncbi.nlm.nih.gov/17914038/) on the effectiveness of influenza vaccine in the community-dwelling elderly to evaluate. Despite several strengths including a prospective cohort design with a large sample size and attempt to control for several important confounders, the reported 50% reduction in all cause mortality for the vaccinated group is an obvious red flag that a substantial bias exists in the execution of this observational study.   

[Letters to the editor](https://pubmed.ncbi.nlm.nih.gov/18160695/) immediately following the article's publication noted that the mortality benefit exceeded all reasonable estimates as influenza mortality during the winter months accounts for 5% or less of total mortality. In these letters, the perceived biased result was attributed to residual and unmeasured confounding. As of March 23 2023 despite these initial concerns, the publication has been cited 233 times, including 13 times in 2022. In only 5 of these 233 citations was the term "bias" also found and in those the discussion was again limited to confounding. Two potential confounding sources mentioned were i) increased vaccinations in the worried well ii) decreased vaccination in those deemed to have too many competing comorbidities for vaccination to make a difference. The majority of articles citing this 2007 publications therefore seem to have taken the results at face value and, as an example, even in 2023 have uncritically written ["prevent influenza-related hospitalizations and deaths among older adults"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9843923/).     

While there is undoubtedly some degree of residual confounding, it seems unlikley that it could explain this magnitude of bias, from a theoretical ceiling of an approximate 5% mortality decrease to the reported 50% decrease.

