# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 1
  - name: Experience/CV
    url: '#experience'
    weight = 2
  - name: Publications
    url: '#publications'
    weight: 3
  - name: Posts
    url: '#posts'
    weight: 4
  - name: Talks
    url: '#talks'
    weight: 5
  - name: Accomplishments
    url: '#accomplishments'
    weight: 6
  - name: Projects
    url: '#projects'
    weight: 7
  - name: Gallery
    url: '#gallery'
    weight: 8
  - name: Contact
    url: '#contact'
    weight: 10
    
